spring.application.name=webchat
spring.datasource.url=jdbc:postgresql://localhost:5432/webchat
spring.datasource.username=postgres
spring.datasource.password=sa123
spring.datasource.driver-class-name=org.postgresql.Driver

app.base-url=http://localhost:8081
server.port=8081
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true


spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vananhcute68@gmail.com
spring.mail.password=fidc frlx euph aldy
spring.mail.properties.mail.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# --- GOOGLE ---
spring.security.oauth2.client.registration.google.client-id=535463670535-8cmg86migqo6gtg7dbgejitv1m4pu7j9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# --- FACEBOOK ---
spring.security.oauth2.client.registration.facebook.client-id=788675920540913
spring.security.oauth2.client.registration.facebook.client-secret=0220670d2828a7bb9ea7088680949cb1
spring.security.oauth2.client.registration.facebook.scope=email,public_profile
spring.security.oauth2.client.registration.facebook.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}


logging.level.org.springframework.security.oauth2=DEBUG

jwt.secret=aee9af71555e097a2b1b92d1b5a1dbc6c2bacae0749947a4b7fbe8fecedfa30e
jwt.access-expiration=3600000
jwt.refresh-expiration=604800000
#15p và 7days

spring.elasticsearch.uris=http://localhost:9200

